export const errorTypes = Object.freeze({
  register: "register",
  logIn: "logIn",
  logOut: "logOut",
  refresh: "refresh",
  addBook: "addBook",
  deleteBook: "deleteBook",
  addBookReview: "addBookReview",
  addPlan: "addPlan",
  changeStatus: "changeStatus",
  finishTraining: "finishTraining",
  addStatistic: "addStatistic",
  endOfSession: "endOfSession",
  common: "common",
});
